<a href="https://colab.research.google.com/github/HarryAI-6748/trendpulse-Harkirat/blob/main/task1_data_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required libraries

In [1]:
import requests
import json
import pandas as pd

Fetching the ID as a json file

In [2]:
api_url = 'https://hacker-news.firebaseio.com/v0/topstories.json'
api_url_2 = 'https://hacker-news.firebaseio.com/v0/item/{id}.json'
stories = {}

data = requests.get(url = api_url, headers = {"User-Agent": "TrendPulse/1.0"})
ids = data.json()

Fetching individual story per ID and defining categories as per their title

In [3]:
stories = {}
Technology = ['AI', 'software', 'tech', 'code', 'computer', 'data', 'cloud', 'API', 'GPU', 'LLM']
Worldnews = ['war', 'government', 'country', 'president', 'election', 'climate', 'attack', 'global']
Sports = ['NFL', 'NBA', 'FIFA', 'sport', 'game', 'team', 'player', 'league', 'championship']
Science = ['research', 'study', 'space', 'physics', 'biology', 'discovery', 'NASA', 'genome']
Entertainment = ['movie', 'film', 'music', 'Netflix', 'game', 'book', 'show', 'award', 'streaming']
for id in ids:
  response = requests.get(url = api_url_2.format(id = id), headers = {"User-Agent": "TrendPulse/1.0"})
  if response.status_code == 200:
    stories[id] = (requests.get(url = api_url_2.format(id = id), headers = {"User-Agent": "TrendPulse/1.0"})).json()
  else:
    print(response.status_code)
    continue
  #print(response.status_code)
#print(stories)

category = {}
collected_stories = {}
for story in stories.values():
  for y in Sports:
    if y in story['title'].split():
      category[story['id']] = 'sports'
  for z in Science:
    if z in story['title'].split():
      category[story['id']] = 'science'
  for w in Entertainment:
    if w in story['title'].split():
      category[story['id']] = 'entertainment'
  for t in Technology:
    if t  in story['title'].split():
      category[story['id']] = 'technology'
  for x in Worldnews:
    if x in story['title'].split():
      category[story['id']] = 'worldnews'

category

{47699814: 'technology',
 47687273: 'technology',
 47689174: 'technology',
 47701971: 'technology',
 47679121: 'technology',
 47689319: 'technology',
 47692661: 'technology',
 47699090: 'technology',
 47699105: 'technology',
 47672295: 'technology',
 47664836: 'technology',
 47696210: 'technology',
 47695647: 'technology',
 47689550: 'technology',
 47627217: 'science',
 47673005: 'technology',
 47672778: 'entertainment',
 47677241: 'technology',
 47661065: 'sports',
 47696723: 'technology',
 47701013: 'technology',
 47696336: 'technology',
 47655408: 'technology',
 47664186: 'entertainment',
 47667672: 'technology',
 47684506: 'technology',
 47699086: 'technology',
 47673541: 'technology',
 47648828: 'technology',
 47652007: 'technology',
 47640728: 'technology',
 47655367: 'technology',
 47656501: 'entertainment',
 47688582: 'technology',
 47662596: 'technology',
 47662945: 'worldnews',
 47665902: 'technology',
 47682908: 'technology',
 47694303: 'technology',
 47690962: 'technology',
 47665207: 'science',
 47682956: 'technology',
 47690415: 'technology',
 47655466: 'technology',
 47690049: 'entertainment',
 47700460: 'technology',
 47688712: 'technology',
 47689135: 'technology',
 47697525: 'technology',
 47637757: 'technology',
 47674950: 'technology',
 47672792: 'technology',
 47693799: 'worldnews',
 47624645: 'technology',
 47693990: 'technology',
 47696600: 'technology',
 47691409: 'science',
 47672642: 'technology',
 47674056: 'technology',
 47683171: 'technology',
 47640875: 'technology',
 47682879: 'technology',
 47682075: 'technology',
 47694522: 'science',
 47629485: 'science',
 47645468: 'technology',
 47639779: 'technology',
 47670377: 'technology',
 47641788: 'technology',
 47620933: 'technology',
 47682435: 'technology',
 47627419: 'worldnews',
 47673576: 'technology',
 47672190: 'sports',
 47630109: 'entertainment'}

Converting json file into data frames so that i can perform multiple operations on them

In [4]:
category_df = pd.DataFrame.from_dict(category, orient='index')
category_df.rename(columns={0: 'category'}, inplace=True)
category = category_df.reset_index()
category.sort_values(by=['index'], inplace=True)
category.rename(columns={'index': 'post_id'}, inplace=True)
category

     post_id    category
69  47620933  technology
53  47624645  technology
14  47627217     science
71  47627419   worldnews
64  47629485     science
..       ...         ...
8   47699105  technology
0   47699814  technology
45  47700460  technology
20  47701013  technology
3   47701971  technology

[75 rows x 2 columns]

In [5]:
stories_df = pd.DataFrame(stories).transpose().reset_index()
stories_df.head()
stories_df.transpose()
stories_df.reset_index().head(50)
stories_df.sort_values(by=['index'], inplace=True)
stories_df.rename(columns={'index': 'post_id'}, inplace=True)
stories_df

,post_id,by,descendants,id,kids,score,time,title,type,url,text
410,47619879,uticus,70,47619879,"[47621546, 47620214, 47620361, 47623695, 47620...",83,1775162417,U.S. is burning through Tomahawk cruise missil...,story,https://www.twz.com/news-features/u-s-is-burni...,NaN
467,47620933,notem,36,47620933,"[47622493, 47623131, 47622169, 47623243, 47622...",59,1775168484,Memo: A language that remembers only the last ...,story,https://danieltemkin.com/Esolangs/Memo/,NaN
260,47621133,benwerd,1,47621133,[47695450],9,1775169629,Design for the Roller Coaster,story,https://pointc.co/design-for-the-roller-coaster/,NaN
476,47621438,codingmoh,61,47621438,"[47624129, 47622020, 47622428, 47622690, 47622...",153,1775171765,Show HN: Made a little Artemis II tracker,story,https://artemis-ii-tracker.com/,Made a little Artemis II tracker for anyone el...
455,47621448,OhMeadhbh,30,47621448,"[47622081, 47624490, 47623480, 47622157, 47623...",79,1775171846,A Few Good Magazines From the 70s and 80s,story,https://www.bi6.us/CO/MG.HTML,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4,47701100,nixass,12,47701100,"[47701263, 47701271, 47702082, 47702050, 47702...",38,1775725897,Creating the Futurescape for the Fifth Element...,story,https://theasc.com/articles/fantastic-voyage-c...,NaN
9,47701233,sixhobbits,85,47701233,"[47701555, 47702066, 47701620, 47702263, 47701...",105,1775726728,Claude mixes up who said what and that's not OK,story,https://dwyer.co.za/static/claude-mixes-up-who...,NaN
36,47701433,robtherobber,5,47701433,"[47702138, 47702185, 47701936, 47702004, 47701...",14,1775728411,America Has Lost the Arab World,story,https://www.foreignaffairs.com/iran/america-ha...,NaN
5,47701572,eigenspace,3,47701572,"[47702121, 47702120]",16,1775729419,"Wit, unker, Git: The lost medieval pronouns of...",story,https://www.bbc.com/future/article/20260408-th...,NaN
31,47701971,gpi,0,47701971,NaN,4,1775731923,AI and remote work is a disaster for junior so...,story,https://medium.com/@lukas_kosinski/ai-and-remo...,NaN

In [10]:
un_df = pd.merge(category, stories_df, on='post_id', how='outer')
un_df.rename(columns = {'descendants':'num_comments', 'by': 'author'}, inplace=True)
un = un_df.drop(columns=['id', 'kids', 'type', 'url', 'text', 'time'])
un['collected_at'] = pd.Timestamp.now()
Tot_Stories = un['post_id'].count()
un

,post_id,category,author,num_comments,score,title,collected_at
0,47619879,NaN,uticus,70,83,U.S. is burning through Tomahawk cruise missil...,2026-04-09 11:38:49.000194
1,47620933,technology,notem,36,59,Memo: A language that remembers only the last ...,2026-04-09 11:38:49.000194
2,47621133,NaN,benwerd,1,9,Design for the Roller Coaster,2026-04-09 11:38:49.000194
3,47621438,NaN,codingmoh,61,153,Show HN: Made a little Artemis II tracker,2026-04-09 11:38:49.000194
4,47621448,NaN,OhMeadhbh,30,79,A Few Good Magazines From the 70s and 80s,2026-04-09 11:38:49.000194
...,...,...,...,...,...,...,...
495,47701100,NaN,nixass,12,38,Creating the Futurescape for the Fifth Element...,2026-04-09 11:38:49.000194
496,47701233,NaN,sixhobbits,85,105,Claude mixes up who said what and that's not OK,2026-04-09 11:38:49.000194
497,47701433,NaN,robtherobber,5,14,America Has Lost the Arab World,2026-04-09 11:38:49.000194
498,47701572,NaN,eigenspace,3,16,"Wit, unker, Git: The lost medieval pronouns of...",2026-04-09 11:38:49.000194
499,47701971,technology,gpi,0,4,AI and remote work is a disaster for junior so...,2026-04-09 11:38:49.000194

Making a new folder called data

In [11]:
from pathlib import Path
Path("data").mkdir(exist_ok=True)

Converting the data frame to json file and saving in data folder

In [12]:
un.to_json("data/trends_20260409.json")
saved_path = "data/trends_20260409.json"
print(f"Collected {Tot_Stories} stories. Saved to {saved_path}")

Collected 500 stories. Saved to data/trends_20260409.json