<a href="https://colab.research.google.com/github/HarryAI-6748/trendpulse-Harkirat/blob/main/task1_data_collection_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required libraries

In [3]:
import requests
import json
import pandas as pd

Defining the URL - Free  REST API

In [13]:
url = "https://restcountries.com/v3.1/all"

Listing out the total number of possible parameters

In [24]:
params = {"fields": "name,population,region,area,flags,capital,currencies,languages,borders,tld,unMember,independent,demonyms,landlocked,subregion,continents"}
params['fields']

'name,population,region,area,flags,capital,currencies,languages,borders,tld,unMember,independent,demonyms,landlocked,subregion,continents'

Fetching the data from URL using requests library and trying to parse the fetched data into a json file, but i can only fetch 10 parameters at a time

In [25]:
url = "https://restcountries.com/v3.1/all"
params = {"fields": "name,population,region,area,flags,capital,currencies,languages,borders,tld,unMember,independent,demonyms,landlocked,subregion,continents"}

response = requests.get(url, params)
count_data = response.json()
count_data

{'message': "'fields' query not specified or you're requesting more than 10 fields",
 'status': 400}

Converting the fetched json into data frame with first 10 parameters

In [26]:

url = "https://restcountries.com/v3.1/all"
params = {"fields": "name,population,region,area,flags,capital,currencies,languages,borders,tld"}
response = requests.get(url, params)
count_data = response.json()
df = pd.DataFrame(count_data)
df

,flags,name,currencies,languages,tld,capital,region,borders,area,population
0,"{'png': 'https://flagcdn.com/w320/ci.png', 'sv...","{'common': 'Ivory Coast', 'official': 'Republi...","{'XOF': {'name': 'West African CFA franc', 'sy...",{'fra': 'French'},[.ci],[Yamoussoukro],Africa,"[BFA, GHA, GIN, LBR, MLI]",322463.0,31719275
1,"{'png': 'https://flagcdn.com/w320/it.png', 'sv...","{'common': 'Italy', 'official': 'Italian Repub...","{'EUR': {'name': 'euro', 'symbol': '€'}}","{'ita': 'Italian', 'cat': 'Catalan'}",[.it],[Rome],Europe,"[AUT, FRA, SMR, SVN, CHE, VAT]",301336.0,58927633
2,"{'png': 'https://flagcdn.com/w320/kg.png', 'sv...","{'common': 'Kyrgyzstan', 'official': 'Kyrgyz R...","{'KGS': {'name': 'Kyrgyzstani som', 'symbol': ...","{'kir': 'Kyrgyz', 'rus': 'Russian'}",[.kg],[Bishkek],Asia,"[CHN, KAZ, TJK, UZB]",199951.0,7281800
3,"{'png': 'https://flagcdn.com/w320/pg.png', 'sv...","{'common': 'Papua New Guinea', 'official': 'In...","{'PGK': {'name': 'Papua New Guinean kina', 'sy...","{'eng': 'English', 'hmo': 'Hiri Motu', 'tpi': ...",[.pg],[Port Moresby],Oceania,[IDN],462840.0,11781559
4,"{'png': 'https://flagcdn.com/w320/fj.png', 'sv...","{'common': 'Fiji', 'official': 'Republic of Fi...","{'FJD': {'name': 'Fijian dollar', 'symbol': '$'}}","{'eng': 'English', 'fij': 'Fijian', 'hif': 'Fi...",[.fj],[Suva],Oceania,[],18272.0,900869
...,...,...,...,...,...,...,...,...,...,...
245,"{'png': 'https://flagcdn.com/w320/sg.png', 'sv...","{'common': 'Singapore', 'official': 'Republic ...","{'SGD': {'name': 'Singapore dollar', 'symbol':...","{'eng': 'English', 'zho': 'Chinese', 'msa': 'M...","[.sg, .新加坡, .சிங்கப்பூர்]",[Singapore],Asia,[],710.0,6110200
246,"{'png': 'https://flagcdn.com/w320/cr.png', 'sv...","{'common': 'Costa Rica', 'official': 'Republic...","{'CRC': {'name': 'Costa Rican colón', 'symbol'...",{'spa': 'Spanish'},[.cr],[San José],Americas,"[NIC, PAN]",51100.0,5309625
247,"{'png': 'https://flagcdn.com/w320/rs.png', 'sv...","{'common': 'Serbia', 'official': 'Republic of ...","{'RSD': {'name': 'Serbian dinar', 'symbol': 'д...",{'srp': 'Serbian'},"[.rs, .срб]",[Belgrade],Europe,"[BIH, BGR, HRV, HUN, UNK, MKD, MNE, ROU]",77589.0,6567783
248,"{'png': 'https://flagcdn.com/w320/pl.png', 'sv...","{'common': 'Poland', 'official': 'Republic of ...","{'PLN': {'name': 'Polish złoty', 'symbol': 'zł'}}",{'pol': 'Polish'},[.pl],[Warsaw],Europe,"[BLR, CZE, DEU, LTU, RUS, SVK, UKR]",312679.0,37392000
249,"{'png': 'https://flagcdn.com/w320/jo.png', 'sv...","{'common': 'Jordan', 'official': 'Hashemite Ki...","{'JOD': {'name': 'Jordanian dinar', 'symbol': ...",{'ara': 'Arabic'},"[.jo, الاردن.]",[Amman],Asia,"[IRQ, ISR, PSE, SAU, SYR]",89342.0,11734000

Converting the fetched json into data frame with remaining parameters

In [27]:
url = "https://restcountries.com/v3.1/all"
params = {"fields": "unMember,independent,demonyms,landlocked,subregion,continents"}
response = requests.get(url, params)
count_data = response.json()
df = pd.DataFrame(count_data)
df

,demonyms,independent,unMember,subregion,landlocked,continents
0,"{'eng': {'f': 'Ivorian', 'm': 'Ivorian'}, 'fra...",True,True,Western Africa,False,[Africa]
1,"{'eng': {'f': 'Italian', 'm': 'Italian'}, 'fra...",True,True,Southern Europe,False,[Europe]
2,"{'eng': {'f': 'Kirghiz', 'm': 'Kirghiz'}, 'fra...",True,True,Central Asia,True,[Asia]
3,"{'eng': {'f': 'Papua New Guinean', 'm': 'Papua...",True,True,Melanesia,False,[Oceania]
4,"{'eng': {'f': 'Fijian', 'm': 'Fijian'}, 'fra':...",True,True,Melanesia,False,[Oceania]
...,...,...,...,...,...,...
245,"{'eng': {'f': 'Singaporean', 'm': 'Singaporean...",True,True,South-Eastern Asia,False,[Asia]
246,"{'eng': {'f': 'Costa Rican', 'm': 'Costa Rican...",True,True,Central America,False,[North America]
247,"{'eng': {'f': 'Serbian', 'm': 'Serbian'}, 'fra...",True,True,Southeast Europe,True,[Europe]
248,"{'eng': {'f': 'Polish', 'm': 'Polish'}, 'fra':...",True,True,Central Europe,False,[Europe]
249,"{'eng': {'f': 'Jordanian', 'm': 'Jordanian'}, ...",True,True,Western Asia,False,[Asia]

Upon inspection of all parameters,a data frame with selected parameters is made

In [34]:
url = "https://restcountries.com/v3.1/all"
params = {"fields": "name,population,region,area,languages,borders,unMember,independent,subregion,continents"}

response = requests.get(url, params)
count_data = response.json()
df = pd.DataFrame(count_data)

Checking the data frame data using df.info() method. It provides a concise, high-level summary of a DataFrame’s structure and metadata. It is primarily being used  for exploratory data analysis (EDA) to quickly assess data quality, such as identifying missing values and ensuring correct data types

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         250 non-null    object
 1   languages    250 non-null    object
 2   independent  250 non-null    bool
 3   unMember     250 non-null    bool
 4   region       250 non-null    object
 5   subregion    250 non-null    object
 6   borders      250 non-null    object
 7   area         250 non-null    float64
 8   population   250 non-null    int64
 9   continents   250 non-null    object
dtypes: bool(2), float64(1), int64(1), object(6)
memory usage: 16.2+ KB

Using df.describe() method to generate a statistical summary of a DataFrame's  numerical columns. It provides a quick overview of the data's central tendency, dispersion, and distribution shape.

In [32]:

df.describe()

               area    population
count  2.500000e+02  2.500000e+02
mean   6.010389e+05  3.207798e+07
std    1.912575e+06  1.319655e+08
min    4.900000e-01  0.000000e+00
25%    1.194250e+03  2.233542e+05
50%    6.492950e+04  5.279123e+06
75%    3.841505e+05  2.037166e+07
max    1.709825e+07  1.417492e+09

Using df.describe() method to generate a statistical summary of a DataFrame's all columns

In [38]:
df.describe(include = 'all')

,name,languages,independent,unMember,region,subregion,borders,area,population,continents
count,250,250,250,250,250,250,250,2.500000e+02,2.500000e+02,250
unique,250,142,2,2,6,25,159,NaN,NaN,8
top,"{'common': 'Ivory Coast', 'official': 'Republi...",{'eng': 'English'},True,True,Africa,Caribbean,[],NaN,NaN,[Africa]
freq,1,39,195,192,59,28,86,NaN,NaN,58
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.010389e+05,3.207798e+07,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.912575e+06,1.319655e+08,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.900000e-01,0.000000e+00,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.194250e+03,2.233542e+05,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.492950e+04,5.279123e+06,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.841505e+05,2.037166e+07,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.709825e+07,1.417492e+09,NaN

Using df.head() to have a quick visual inspection of the dataset to verify data loading, check column names, and understand the general structure without displaying the entire dataset

In [33]:

df.head()

,name,languages,independent,unMember,region,subregion,borders,area,population,continents
0,"{'common': 'Ivory Coast', 'official': 'Republi...",{'fra': 'French'},True,True,Africa,Western Africa,"[BFA, GHA, GIN, LBR, MLI]",322463.0,31719275,[Africa]
1,"{'common': 'Italy', 'official': 'Italian Repub...","{'ita': 'Italian', 'cat': 'Catalan'}",True,True,Europe,Southern Europe,"[AUT, FRA, SMR, SVN, CHE, VAT]",301336.0,58927633,[Europe]
2,"{'common': 'Kyrgyzstan', 'official': 'Kyrgyz R...","{'kir': 'Kyrgyz', 'rus': 'Russian'}",True,True,Asia,Central Asia,"[CHN, KAZ, TJK, UZB]",199951.0,7281800,[Asia]
3,"{'common': 'Papua New Guinea', 'official': 'In...","{'eng': 'English', 'hmo': 'Hiri Motu', 'tpi': ...",True,True,Oceania,Melanesia,[IDN],462840.0,11781559,[Oceania]
4,"{'common': 'Fiji', 'official': 'Republic of Fi...","{'eng': 'English', 'fij': 'Fijian', 'hif': 'Fi...",True,True,Oceania,Melanesia,[],18272.0,900869,[Oceania]